apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: customer-pod
      app: customer
  template:
    metadata:
      name: customer-pod
      labels:
        name: customer-pod
        app: customer

    spec:
      containers:
      - name: customer
        image: gar2000b/customer-service
        ports:
        - containerPort: 9082
