apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-application-deployment
  annotations: 
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: loan-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loan-application-pod
      app: loan-application
  template:
    metadata:
      name: loan-application-pod
      labels:
        name: loan-application-pod
        app: loan-application

    spec:
      containers:
      - name: loan-application
        image: gar2000b/loan-application-service
        ports:
        - containerPort: 9080
