apiVersion: v1
kind: ServiceAccount
metadata:
  name: loan-application
---
apiVersion: v1
kind: Pod
metadata:
  name: loan-application
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "social-insurance-workflow:9081"
spec:
  containers:
  - name: loan-application
    image: gar2000b/loan-application-service
    ports:
    - containerPort: 9080
      name: http
    env:
    - name: SOCIAL_INSURANCE_WORKFLOW_SERVICE_URL
      value: "http://localhost:9081"
  serviceAccountName: loan-application
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'loan-application-service-load-balancer'
  namespace: 'default'
  labels:
    app: 'loan-application'
spec:
  ports:
    - protocol: 'TCP'
      port: 9080
      targetPort: 9080
  selector:
    app: 'loan-application'
  type: 'LoadBalancer'
  loadBalancerIP: ''
  