apiVersion: v1
kind: Service
metadata:
  name: loan-application-service
  labels:
    name: loan-application-service-service
    app: loan-application
spec:
  type: LoadBalancer
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    name: loan-application-pod
    app: loan-application
