apiVersion: v1
kind: Service
metadata:
  name: external-test
  labels:
    app: external-test
    service: external-test
spec:
  type: NodePort
  ports:
  - port: 9086
    name: http
  selector:
    app: external-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-test
  labels:
    account: external-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-test
  labels:
    app: external-test
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-test
      version: v1
  template:
    metadata:
      labels:
        app: external-test
        version: v1
    spec:
      serviceAccountName: external-test
      containers:
      - name: external-test
        image: gar2000b/external-test-service:istio2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9086
