apiVersion: v1
kind: Service
metadata:
  name: loan-application
  labels:
    app: loan-application
    service: loan-application
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: loan-application
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loan-application
  labels:
    account: loan-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-application
  labels:
    app: loan-application
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-application
      version: v1
  template:
    metadata:
      labels:
        app: loan-application
        version: v1
    spec:
      serviceAccountName: loan-application
      containers:
      - name: loan-application
        image: gar2000b/loan-application-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
