apiVersion: v1
kind: Service
metadata:
  name: social-insurance-workflow
  labels:
    app: social-insurance-workflow
    service: social-insurance-workflow
spec:
  ports:
  - port: 9081
    name: http
  selector:
    app: social-insurance-workflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: social-insurance-workflow
  labels:
    account: social-insurance-workflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-insurance-workflow
  labels:
    app: social-insurance-workflow
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-insurance-workflow
      version: v1
  template:
    metadata:
      labels:
        app: social-insurance-workflow
        version: v1
    spec:
      serviceAccountName: social-insurance-workflow
      containers:
      - name: social-insurance-workflow
        image: gar2000b/social-insurance-workflow-service:istio
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9081
