apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    name: customer-service-service
    app: customer
spec:
  type: LoadBalancer
  ports:
  - port: 9082
    targetPort: 9082
  selector:
    name: customer-pod
    app: customer
