apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    name: customer
    app: customer
spec:
  type: ClusterIP
  ports:
  - port: 9082
    targetPort: 9082
  selector:
    name: customer
    app: customer
