apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-insurance-workflow
  labels:
    app: social-insurance-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: social-insurance-workflow
      app: social-insurance-workflow
  template:
    metadata:
      name: social-insurance-workflow
      annotations: 
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "fraud-check:9083"
        "consul.hashicorp.com/connect-service-upstreams": "customer:9082"
        "consul.hashicorp.com/connect-service-upstreams": "social-insurance-verification:9085"
      labels:
        name: social-insurance-workflow
        app: social-insurance-workflow

    spec:
      containers:
      - name: social-insurance-workflow
        image: gar2000b/social-insurance-workflow-service
        ports:
        - containerPort: 9081
