apiVersion: v1
kind: Service
metadata:
  name: social-insurance-workflow
  labels:
    name: social-insurance-workflow
    app: social-insurance-workflow
spec:
  type: ClusterIP
  ports:
  - port: 9081
    targetPort: 9081
  selector:
    name: social-insurance-workflow
    app: social-insurance-workflow
