apiVersion: v1
kind: Service
metadata:
  name: fraud-check
  labels:
    name: fraud-check
    app: fraud-check
spec:
  type: ClusterIP
  ports:
  - port: 9083
    targetPort: 9083
  selector:
    name: fraud-check
    app: fraud-check
