apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-application
  labels:
    app: loan-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loan-application
      app: loan-application
  template:
    metadata:
      name: loan-application
      annotations: 
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "social-insurance-workflow:9081"
      labels:
        name: loan-application
        app: loan-application

    spec:
      containers:
      - name: loan-application
        image: gar2000b/loan-application-service
        ports:
        - containerPort: 9080
